CREATE TABLE currency
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code   VARCHAR(255)                            NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    symbol VARCHAR(255),
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

CREATE TABLE exchange
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pscp_id   BIGINT                                  NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    rate      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_exchange PRIMARY KEY (id)
);

CREATE TABLE latest_exchange
(
    pscp_id   BIGINT           NOT NULL,
    rate      DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP        NOT NULL,
    CONSTRAINT pk_latest_exchange PRIMARY KEY (pscp_id)
);

CREATE TABLE provider
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    api_key VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_provider PRIMARY KEY (id)
);

CREATE TABLE provider_supported_currency_pairs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_id BIGINT                                  NOT NULL,
    src_id      BIGINT                                  NOT NULL,
    dst_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_provider_supported_currency_pairs PRIMARY KEY (id)
);

ALTER TABLE provider_supported_currency_pairs
    ADD CONSTRAINT uc_08dcb9fb132baddc1db03a226 UNIQUE (provider_id, src_id, dst_id);

ALTER TABLE currency
    ADD CONSTRAINT uc_currency_code UNIQUE (code);

ALTER TABLE provider
    ADD CONSTRAINT uc_provider_name UNIQUE (name);

ALTER TABLE exchange
    ADD CONSTRAINT FK_EXCHANGE_ON_PSCP FOREIGN KEY (pscp_id) REFERENCES provider_supported_currency_pairs (id);

ALTER TABLE latest_exchange
    ADD CONSTRAINT FK_LATEST_EXCHANGE_ON_PSCP FOREIGN KEY (pscp_id) REFERENCES provider_supported_currency_pairs (id);

ALTER TABLE provider_supported_currency_pairs
    ADD CONSTRAINT FK_PROVIDER_SUPPORTED_CURRENCY_PAIRS_ON_DST FOREIGN KEY (dst_id) REFERENCES currency (id);

ALTER TABLE provider_supported_currency_pairs
    ADD CONSTRAINT FK_PROVIDER_SUPPORTED_CURRENCY_PAIRS_ON_PROVIDER FOREIGN KEY (provider_id) REFERENCES provider (id);

ALTER TABLE provider_supported_currency_pairs
    ADD CONSTRAINT FK_PROVIDER_SUPPORTED_CURRENCY_PAIRS_ON_SRC FOREIGN KEY (src_id) REFERENCES currency (id);